
CREATE TABLE QUOTE(

    QUOTEID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    QUOTE   TEXT NOT NULL,
    GENRE   VARCHAR(20),
    SOURCE  TEXT,
    QUOTEDATE DATE,
    ERA     VARCHAR(20),

    CONSTRAINT PK_QUOTE PRIMARY KEY(QUOTEID)

);